CREATE TABLE IF NOT EXISTS risk_assessments (
                                                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                                business_id BIGINT NOT NULL,
                                                policy_id BIGINT,
                                                owner_id BIGINT NOT NULL,
                                                risk_score DECIMAL(5,2) NOT NULL,
    risk_level VARCHAR(30) NOT NULL,
    risk_factors VARCHAR(2000),
    recommendation VARCHAR(2000),
    assessed_by BIGINT NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL
    );

CREATE INDEX IF NOT EXISTS idx_risk_business
    ON risk_assessments(business_id);

CREATE INDEX IF NOT EXISTS idx_risk_owner
    ON risk_assessments(owner_id);


CREATE TABLE IF NOT EXISTS simulations (
                                           id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                           business_id BIGINT NOT NULL,
                                           policy_id BIGINT,
                                           owner_id BIGINT NOT NULL,
                                           scenario_name VARCHAR(255) NOT NULL,
    scenario_input VARCHAR(4000),
    projected_risk_score DECIMAL(5,2),
    projected_risk_level VARCHAR(30),
    result_summary VARCHAR(4000),
    status VARCHAR(30) NOT NULL,
    created_by BIGINT NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL
    );

CREATE INDEX IF NOT EXISTS idx_simulation_business
    ON simulations(business_id);

CREATE INDEX IF NOT EXISTS idx_simulation_owner
    ON simulations(owner_id);


CREATE TABLE IF NOT EXISTS risk_mitigations (
                                                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

                                                assessment_id BIGINT NOT NULL,
                                                business_id BIGINT NOT NULL,
                                                owner_id BIGINT NOT NULL,

                                                mitigation_title VARCHAR(255) NOT NULL,
    description VARCHAR(2000),
    priority VARCHAR(30) NOT NULL,
    status VARCHAR(30) NOT NULL,

    assigned_to BIGINT,
    target_date DATE,
    completed_at TIMESTAMP,

    created_by BIGINT NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL
    );

CREATE INDEX IF NOT EXISTS idx_mitigation_assessment
    ON risk_mitigations(assessment_id);

CREATE INDEX IF NOT EXISTS idx_mitigation_business
    ON risk_mitigations(business_id);

CREATE INDEX IF NOT EXISTS idx_mitigation_owner
    ON risk_mitigations(owner_id);

CREATE INDEX IF NOT EXISTS idx_mitigation_status
    ON risk_mitigations(status);