-- =========================================================
-- POLICIES TABLE
-- =========================================================

CREATE TABLE IF NOT EXISTS policies (
                                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

                                        business_id BIGINT NOT NULL,
                                        owner_id BIGINT NOT NULL,

                                        policy_number VARCHAR(100) NOT NULL UNIQUE,
    policy_type VARCHAR(50) NOT NULL,

    coverage_amount DECIMAL(19,2) NOT NULL,
    coverage_details VARCHAR(1000),
    coverage_location VARCHAR(255),

    premium_amount DECIMAL(19,2) NOT NULL,

    start_date DATE NOT NULL,
    end_date DATE NOT NULL,

    tenure_value INT NOT NULL DEFAULT 1,
    tenure_unit VARCHAR(10) NOT NULL DEFAULT 'YEARS',
    payment_frequency VARCHAR(10) NOT NULL DEFAULT 'YEARLY',

    status VARCHAR(30) NOT NULL,
    description VARCHAR(1000),

    -- Policy cancellation support
    previous_status VARCHAR(30),
    cancellation_reason VARCHAR(1000),

    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL
    );


-- =========================================================
-- ENSURE EXISTING POLICY COLUMNS EXIST
-- =========================================================

ALTER TABLE policies
    ADD COLUMN IF NOT EXISTS tenure_value
    INT NOT NULL DEFAULT 1;

ALTER TABLE policies
    ADD COLUMN IF NOT EXISTS tenure_unit
    VARCHAR(10) NOT NULL DEFAULT 'YEARS';

ALTER TABLE policies
    ADD COLUMN IF NOT EXISTS payment_frequency
    VARCHAR(10) NOT NULL DEFAULT 'YEARLY';


-- =========================================================
-- POLICY COVERAGE AND LOCATION COLUMNS
-- =========================================================

ALTER TABLE policies
    ADD COLUMN IF NOT EXISTS coverage_details
    VARCHAR(1000);

ALTER TABLE policies
    ADD COLUMN IF NOT EXISTS coverage_location
    VARCHAR(255);


-- =========================================================
-- POLICY CANCELLATION COLUMNS
-- =========================================================

ALTER TABLE policies
    ADD COLUMN IF NOT EXISTS previous_status
    VARCHAR(30);

ALTER TABLE policies
    ADD COLUMN IF NOT EXISTS cancellation_reason
    VARCHAR(1000);


-- =========================================================
-- POLICY INDEXES
-- =========================================================

CREATE UNIQUE INDEX IF NOT EXISTS idx_policy_number
    ON policies(policy_number);

CREATE INDEX IF NOT EXISTS idx_policy_owner
    ON policies(owner_id);

CREATE INDEX IF NOT EXISTS idx_policy_business
    ON policies(business_id);


-- =========================================================
-- MOCK PAYMENT RECORDS
-- =========================================================

CREATE TABLE IF NOT EXISTS policy_payments (
                                               id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

                                               policy_id BIGINT NOT NULL,
                                               owner_id BIGINT NOT NULL,

                                               amount DECIMAL(19,2) NOT NULL,
    payment_date TIMESTAMP NOT NULL,

    status VARCHAR(30) NOT NULL,
    transaction_reference VARCHAR(100) NOT NULL UNIQUE,

    created_at TIMESTAMP NOT NULL,

    CONSTRAINT fk_payment_policy
    FOREIGN KEY (policy_id)
    REFERENCES policies(id)
    );


-- =========================================================
-- PAYMENT INDEXES
-- =========================================================

CREATE INDEX IF NOT EXISTS idx_payment_policy
    ON policy_payments(policy_id);

CREATE INDEX IF NOT EXISTS idx_payment_owner
    ON policy_payments(owner_id);

CREATE INDEX IF NOT EXISTS idx_payment_status
    ON policy_payments(status);