CREATE TABLE IF NOT EXISTS business_profiles (
                                                 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                                 owner_id BIGINT NOT NULL,
                                                 business_name VARCHAR(200) NOT NULL,
    registration_number VARCHAR(100) NOT NULL UNIQUE,
    business_type VARCHAR(50) NOT NULL,
    industry VARCHAR(100) NOT NULL,
    address VARCHAR(500) NOT NULL,
    city VARCHAR(100) NOT NULL,
    state VARCHAR(100) NOT NULL,
    postal_code VARCHAR(20) NOT NULL,
    country VARCHAR(100) NOT NULL,
    contact_email VARCHAR(255) NOT NULL,
    contact_phone VARCHAR(30) NOT NULL,
    annual_revenue DECIMAL(19,2),
    employee_count INTEGER,
    established_date DATE,

    -- Detailed business information
    business_description VARCHAR(2000),
    website VARCHAR(255),
    branch_count INTEGER,
    premises_type VARCHAR(30),
    previous_insurance_claims INTEGER,
    existing_insurance BOOLEAN,

    status VARCHAR(30) NOT NULL DEFAULT 'ACTIVE',
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL
    );

CREATE INDEX IF NOT EXISTS idx_business_owner_id
    ON business_profiles(owner_id);


-- Migration for existing business_profiles tables
ALTER TABLE business_profiles
    ADD COLUMN IF NOT EXISTS business_description VARCHAR(2000);

ALTER TABLE business_profiles
    ADD COLUMN IF NOT EXISTS website VARCHAR(255);

ALTER TABLE business_profiles
    ADD COLUMN IF NOT EXISTS branch_count INTEGER;

ALTER TABLE business_profiles
    ADD COLUMN IF NOT EXISTS premises_type VARCHAR(30);

ALTER TABLE business_profiles
    ADD COLUMN IF NOT EXISTS previous_insurance_claims INTEGER;

ALTER TABLE business_profiles
    ADD COLUMN IF NOT EXISTS existing_insurance BOOLEAN;


-- Business deletion requests
CREATE TABLE IF NOT EXISTS business_deletion_requests (
                                                          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                                          business_id BIGINT NOT NULL,
                                                          owner_id BIGINT NOT NULL,
                                                          reviewer_id BIGINT,
                                                          reason VARCHAR(1000),
    status VARCHAR(30) NOT NULL DEFAULT 'PENDING',
    created_at TIMESTAMP NOT NULL,
    reviewed_at TIMESTAMP
    );

CREATE INDEX IF NOT EXISTS idx_deletion_owner
    ON business_deletion_requests(owner_id);

CREATE INDEX IF NOT EXISTS idx_deletion_status
    ON business_deletion_requests(status);